# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'

steps:
- task: NuGetCommand@2
  displayName: Nuget restore
  inputs:
    command: 'restore'
    restoreSolution: '**/*.sln'
    feedsToUse: 'select'
    vstsFeed: 'f7331d67-128d-48fa-ab70-2bf4cd932e21/cb4d53e4-2f04-4fa1-b1c1-790ddbce8eb0'
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'
- task: AzureWebApp@1
  inputs:
    azureSubscription: 'Azure subscription 1(ae7082e1-108c-44c0-924b-975ca0362834)'
    appType: 'webAppLinux'
    appName: 'Chessica'
    deployToSlotOrASE: true
    resourceGroupName: 'Chessica'
    slotName: 'production'
    package: '$(System.DefaultWorkingDirectory)/**/*.zip'
    runtimeStack: 'DOTNETCORE|6.0'